### ISSUE TITLE
Remove security breaches

### ISSUE THREAD

**Issue by vojtatranta** [JkmAS/CompassDirectoryBrowser#1]
Escape all $_GET params in every string, it is easily hackable - you can run your own PHP (SQL) code just by changing URL, needless talking about JS code execution.
Remove private access to property / method, because with it they cannot be overridden.
In method showPermission() remove unnecessary index (0 => 'xyz' is useless, write 'xyz', 'abc')
Use http_build_query instead of dir=xyz

Never allow your method to have more than one cycle in it.

Use PHP as it was originally meant - as templating engine ->
instead (in template)

```
<?php                 
                    foreach ($dirScan->breadCrumbs as $breadCrumb) {
                        echo "<b> ".$breadCrumb." </b>/";
                    }
                ?>  
```

use

```
<?php foreach($dirScan->breadCrumbs as $crumb): ?>
<b><?= $crumb ?></b>
<?php endforeach; ?>
```

**Comment by JkmAS** [comment]
Escape..., I forgot:/. And thank you for other comments. I will fix it asap.
